### ISSUE TITLE
[FEATURE] Change the gh action tests to run faster

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#2319]
**Describe how this feature will help us improve**
Currently, tests on every push to repo take too much time.

**Is your proposal related to a problem?**
Change workflow to run test only when it's needed like this:
```
on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop
 ``` 

**Describe the solution you'd considered**
A concise description of your preferred solution. Things to address include:

  - Details of the technical implementation
  - Tradeoffs made in design decisions
  - Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.

**Additional context**
Anything you would like to add but was not sure which section it fits.
