### ISSUE TITLE
[BUG] Overridden other component's CSS variable

### ISSUE THREAD

**Issue by leoj3n** [vuestorefront/storefront-ui#2349]
For the css variable generation script, it makes the description be "Overridden other component's CSS variable".

As an English sentence, this does not make sense to me; I' don't understand what it saying.

Can someone clarify is meant by "Overridden other component's CSS variable"?

Perhaps this can be rephrased to be more clear.

**Comment by leoj3n** [comment]
If you have a `scss` file like that:

```scss
.sf-device {
  --device-not-used: 8px;
  --device-yes-used: 9px;

  width: var(--device-yes-used);
}
```

Then `yarn run update-components-docs` generates an array like that:

```js
[ [ [ '--device-yes-used', '' ] ], [ [ '--device-not-used', '8px' ] ] ]
```

Which results in a Storybook like that:

![](https://user-images.githubusercontent.com/990216/159662869-be56bd9b-6c02-4ed3-854e-51f34e29231e.png)

In this case, it seems as though a CSS variable that is declared but not used will receive the "Overridden other component's CSS variable" description.
